"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const CartaoCredito_1 = require("./CartaoCredito");
const Boleto_1 = require("./Boleto");
const Pix_1 = require("./Pix");
const processarPagamento_1 = require("./processarPagamento");
const prompt_sync_1 = __importDefault(require("prompt-sync"));
const chalk_1 = __importDefault(require("chalk"));
const prompt = (0, prompt_sync_1.default)();
const valorCartao = Number(prompt('Digite o valor para pagar com ' + chalk_1.default.yellow('Cartão de Crédito: ')));
const valorBoleto = Number(prompt('Digite o valor para pagar com ' + chalk_1.default.yellow('Boleto: ')));
const valorPix = Number(prompt('Digite o valor para pagar com ' + chalk_1.default.yellow('Pix: ')));
const pagamentoCartao = new CartaoCredito_1.CartaoCredito();
const pagamentoBoleto = new Boleto_1.Boleto();
const pagamentoPix = new Pix_1.Pix();
(0, processarPagamento_1.processarPagamento)(pagamentoCartao, valorCartao);
(0, processarPagamento_1.processarPagamento)(pagamentoBoleto, valorBoleto);
(0, processarPagamento_1.processarPagamento)(pagamentoPix, valorPix);
